title: Levi Sprung
baseURL: https://levisprung.com
languageCode: en-us
theme: hugo-theme-mini
logo: avatar.png
defaultContentLanguage: en
# disqusShortname: your-disqus-shortname





params:
  social:
    github: https://github.com/levibsprung/
    spotify: https://open.spotify.com/user/9c7y9lzudp57ixe94b0ajr3ux?si=e912596ebc36460a
    linkedin: https://www.linkedin.com/in/levi-sprung
    email: mailto:levibsprung@gmail.com
  author: Levi Sprung
  bio: Aspiring Software Engineer and Data Scientist
  description: Personal website and blog
  env: production
# googleAnalytics: your-google-analytics-id


caches:
  images:
    dir: :cacheDir/images

